[[host]]
name='h1'
[[host.if]]
name='eth0'
peer='h2'
peer-if='eth2'
[[host.if]]
name='eth1'
peer='h3'
peer-if='eth3'


[[host]]
name='h2'
[[host.if]]
name='eth2'
[[host.if]]
name='eth4'


[[host]]
name='h3'
[[host.if]]
name='eth3'
